version: "3.8"

services:
  regularbuspostgres:
    container_name: regularbus-db-postgres-container
    image: library/postgres:12.10-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=60s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "vending_system_regularbus"
      POSTGRES_USER: "${POSTGRES_USER:-what}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-whatwhat}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./regularbus:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U what -d vending_system_regularbus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3.10.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

#  cashregister:
#    container_name: cashregister-container
#    image: cashregister:latest
#    build:
#      dockerfile: "cashregister/Dockerfile"
#    depends_on:
#      - rabbitmq
#    links:
#      - "rabbitmq:rabbitmq"
#    environment:
#      - CASHREG_RABBITMQ_HOST=rabbitmq
#      - CASHREG_RABBITMQ_USERNAME=what
#      - CASHREG_RABBITMQ_PASSWORD=what

#  regularbus:
#    container_name: regularbus-container
#    image: regularbus:latest
#    build:
#      dockerfile: "regularbus/Dockerfile"
#    depends_on:
#      - rabbitmq
#    links:
#      - "rabbitmq:rabbitmq"
#      - "regularbuspostgres:regularbuspostgres"
#    environment:
#      - CASHREG_RABBITMQ_HOST=rabbitmq
#      - CASHREG_RABBITMQ_USERNAME=what
#      - CASHREG_RABBITMQ_PASSWORD=what
#      - REGULARBUS_DB_HOST=regularbuspostgres
#      - REGULARBUS_SERVER_PORT=8080
#      - REGULARBUS_APPLICATION_NAME=vending_system_regularbus

#  webserver:
#    image: nginx:alpine
#    container_name: webserver
#    restart: unless-stopped
#    tty: true
#    ports:
#      - "8282:80"
##      - "443:443"
#    volumes:
#      - ./pub:/usr/share/nginx/html
##      - ./pub:/var/www
#      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app2.conf