server:
  port: ${DIAG_SERVER_PORT:8081}

spring:
  security:
    user:
      name: ${DIAG_ADMIN_NAME:admin}
      password: ${DIAG_ADMIN_PASSWORD:admin}
  boot:
    admin:
      client:
        url: http://localhost:8081
        username: ${DIAG_ADMIN_NAME:admin}
        password: ${DIAG_ADMIN_PASSWORD:admin}
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always